project:
  type: website
  output-dir: "docs"

website:
  title: "Silas Pickhardt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: michiganfire.qmd
        text: Michigan Wildfire Risk Assesement
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

